#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : telemetrics-client
Version  : 1.16.3
Release  : 96
URL      : https://github.com/clearlinux/telemetrics-client/releases/download/v1.16.3/telemetrics-client-1.16.3.tar.gz
Source0  : https://github.com/clearlinux/telemetrics-client/releases/download/v1.16.3/telemetrics-client-1.16.3.tar.gz
Summary  : Telemetrics library
Group    : Development/Tools
License  : LGPL-2.1
Requires: telemetrics-client-bin
Requires: telemetrics-client-config
Requires: telemetrics-client-autostart
Requires: telemetrics-client-lib
Requires: telemetrics-client-data
Requires: telemetrics-client-license
Requires: telemetrics-client-man
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libdw)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(libsystemd)
Patch1: wait_longer.patch

%description
No detailed description available

%package autostart
Summary: autostart components for the telemetrics-client package.
Group: Default

%description autostart
autostart components for the telemetrics-client package.


%package bin
Summary: bin components for the telemetrics-client package.
Group: Binaries
Requires: telemetrics-client-data
Requires: telemetrics-client-config
Requires: telemetrics-client-license
Requires: telemetrics-client-man

%description bin
bin components for the telemetrics-client package.


%package config
Summary: config components for the telemetrics-client package.
Group: Default

%description config
config components for the telemetrics-client package.


%package data
Summary: data components for the telemetrics-client package.
Group: Data

%description data
data components for the telemetrics-client package.


%package dev
Summary: dev components for the telemetrics-client package.
Group: Development
Requires: telemetrics-client-lib
Requires: telemetrics-client-bin
Requires: telemetrics-client-data
Provides: telemetrics-client-devel

%description dev
dev components for the telemetrics-client package.


%package lib
Summary: lib components for the telemetrics-client package.
Group: Libraries
Requires: telemetrics-client-data
Requires: telemetrics-client-license

%description lib
lib components for the telemetrics-client package.


%package license
Summary: license components for the telemetrics-client package.
Group: Default

%description license
license components for the telemetrics-client package.


%package man
Summary: man components for the telemetrics-client package.
Group: Default

%description man
man components for the telemetrics-client package.


%prep
%setup -q -n telemetrics-client-1.16.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532731324
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1532731324
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/telemetrics-client
cp LICENSE.LGPL-2.1 %{buildroot}/usr/share/doc/telemetrics-client/LICENSE.LGPL-2.1
%make_install
## install_append content
mkdir %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../telemd.path %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/telemd.path
mkdir %{buildroot}/usr/lib/systemd/system/sockets.target.wants
ln -s ../telemd.socket %{buildroot}/usr/lib/systemd/system/sockets.target.wants/telemd.socket
mkdir %{buildroot}/usr/lib/systemd/system/timers.target.wants
ln -s ../hprobe.timer %{buildroot}/usr/lib/systemd/system/timers.target.wants/hprobe.timer
mkdir %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -s ../telemd-update-trigger.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/telemd-update-trigger.service
ln -s ../pstore-clean.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/pstore-clean.service
ln -s ../pstore-probe.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/pstore-probe.service
ln -s ../oops-probe.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/oops-probe.service
ln -s ../klogscanner.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/klogscanner.service
ln -s ../journal-probe.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/journal-probe.service
ln -s ../bert-probe.service  %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/bert-probe.service
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/oops-probe.service %{buildroot}/usr/share/clr-service-restart/oops-probe.service
ln -sf /usr/lib/systemd/system/klogscanner.service %{buildroot}/usr/share/clr-service-restart/klogscanner.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/bert-probe.service
/usr/lib/systemd/system/multi-user.target.wants/journal-probe.service
/usr/lib/systemd/system/multi-user.target.wants/klogscanner.service
/usr/lib/systemd/system/multi-user.target.wants/oops-probe.service
/usr/lib/systemd/system/multi-user.target.wants/pstore-clean.service
/usr/lib/systemd/system/multi-user.target.wants/pstore-probe.service
/usr/lib/systemd/system/multi-user.target.wants/telemd.path
/usr/lib/systemd/system/sockets.target.wants/telemd.socket
/usr/lib/systemd/system/timers.target.wants/hprobe.timer

%files bin
%defattr(-,root,root,-)
/usr/bin/bertprobe
/usr/bin/crashprobe
/usr/bin/hprobe
/usr/bin/journalprobe
/usr/bin/klogscanner
/usr/bin/oopsprobe
/usr/bin/pstoreclean
/usr/bin/pstoreprobe
/usr/bin/telem-record-gen
/usr/bin/telem_journal
/usr/bin/telemctl
/usr/bin/telemd

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/bert-probe.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/journal-probe.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/klogscanner.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/oops-probe.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/pstore-clean.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/pstore-probe.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/telemd.path
%exclude /usr/lib/systemd/system/sockets.target.wants/telemd.socket
%exclude /usr/lib/systemd/system/timers.target.wants/hprobe.timer
/usr/lib/systemd/system.conf.d/40-core-ulimit.conf
/usr/lib/systemd/system/bert-probe.service
/usr/lib/systemd/system/hprobe.service
/usr/lib/systemd/system/hprobe.timer
/usr/lib/systemd/system/journal-probe.service
/usr/lib/systemd/system/klogscanner.service
/usr/lib/systemd/system/oops-probe.service
/usr/lib/systemd/system/pstore-clean.service
/usr/lib/systemd/system/pstore-probe.service
/usr/lib/systemd/system/telemd-update-trigger.service
/usr/lib/systemd/system/telemd.path
/usr/lib/systemd/system/telemd.service
/usr/lib/systemd/system/telemd.socket
/usr/lib/systemd/system/update-triggers.target.wants/telemd-update-trigger.service
/usr/lib/tmpfiles.d/telemetrics-dirs.conf

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/klogscanner.service
/usr/share/clr-service-restart/oops-probe.service
/usr/share/defaults/telemetrics/telemetrics.conf

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libtelemetry.so
/usr/lib64/pkgconfig/libtelemetry.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtelemetry.so.3
/usr/lib64/libtelemetry.so.3.1.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/telemetrics-client/LICENSE.LGPL-2.1

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/telem-record-gen.1
/usr/share/man/man1/telemctl.1
/usr/share/man/man1/telemd.1
/usr/share/man/man3/telemetry.3
/usr/share/man/man3/tm_create_record.3
/usr/share/man/man3/tm_send_record.3
/usr/share/man/man3/tm_set_config_file.3
/usr/share/man/man3/tm_set_payload.3
/usr/share/man/man5/telemetrics.conf.5
